export const RESIZE_TABEL = 'RESIZE_TABEL';
export const CHANGE_TEXT = 'CHANGE_TEXT';
export const CHANGE_TOOLBAR_STYLES = 'CHANGE_TOOLBAR_STYLES';
export const APPLY_STYLE = 'APPLY_STYLE';
export const CHANGE_TITLE = 'CHANGE_TITLE';